const K={users:'unilab_users_v3',bookings:'unilab_bookings_v3',pcs:'unilab_pcs_v3',session:'unilab_session_v3',init:'unilab_initialized_v3'};
const labs=[
{id:'LAB-01',name:'Computer Lab 1',building:'ICT Building',floor:'Ground Floor',capacity:30},
{id:'LAB-02',name:'Computer Lab 2',building:'ICT Building',floor:'1st Floor',capacity:25},
{id:'LAB-03',name:'Computer Lab 3',building:'Science Block',floor:'Ground Floor',capacity:40},
{id:'LAB-04',name:'Computer Lab 4',building:'Science Block',floor:'1st Floor',capacity:35},
{id:'LAB-05',name:'Computer Lab 5',building:'Engineering Block',floor:'2nd Floor',capacity:50},
{id:'LAB-06',name:'Computer Lab 6',building:'Engineering Block',floor:'3rd Floor',capacity:45}];
const slots=[
{id:'08-10',label:'08:00 - 10:00',start:'08:00',end:'10:00'},
{id:'10-12',label:'10:00 - 12:00',start:'10:00',end:'12:00'},
{id:'12-14',label:'12:00 - 14:00',start:'12:00',end:'14:00'},
{id:'14-16',label:'14:00 - 16:00',start:'14:00',end:'16:00'},
{id:'16-18',label:'16:00 - 18:00',start:'16:00',end:'18:00'}];
let page='dashboard';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const today=()=>new Date().toISOString().slice(0,10);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const initials=n=>n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join('')||'U';
const user=()=>read(K.users,[]).find(x=>x.userId===localStorage.getItem(K.session));
const lab=id=>labs.find(x=>x.id===id);
function toast(m,t=''){const x=document.createElement('div');x.className='toast '+t;x.textContent=m;document.getElementById('toast-container').appendChild(x);setTimeout(()=>x.remove(),3000)}
function seed(){if(localStorage.getItem(K.init))return;const now=new Date().toISOString();write(K.users,[
{userId:'student01',fullName:'Demo Student',email:'student@example.com',password:'student123',role:'STUDENT',createdAt:now},
{userId:'lecturer01',fullName:'Demo Lecturer',email:'lecturer@example.com',password:'lecturer123',role:'LECTURER',createdAt:now},
{userId:'admin',fullName:'System Administrator',email:'admin@example.com',password:'admin123',role:'ADMIN',createdAt:now}]);
const pcs=[];labs.forEach(l=>{for(let i=1;i<=l.capacity;i++)pcs.push({pcId:`${l.id}-PC-${String(i).padStart(2,'0')}`,number:`PC-${String(i).padStart(2,'0')}`,labId:l.id,status:'READY',maintenanceNote:'',updatedAt:now})});write(K.pcs,pcs);write(K.bookings,[]);localStorage.setItem(K.init,'1')}
function auth(){document.getElementById('auth-view').classList.remove('hidden');document.getElementById('app-view').classList.add('hidden')}
function app(){const u=user();if(!u)return auth();document.getElementById('auth-view').classList.add('hidden');document.getElementById('app-view').classList.remove('hidden');document.getElementById('sidebar-name').textContent=u.fullName;document.getElementById('sidebar-role').textContent=u.role==='ADMIN'?'System Administrator':u.role;document.getElementById('sidebar-avatar').textContent=initials(u.fullName);document.getElementById('topbar-avatar').textContent=initials(u.fullName);document.getElementById('topbar-date').textContent=new Date().toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short',year:'numeric'});nav();render(page)}
function nav(){const u=user(),n=document.getElementById('main-nav');n.innerHTML=u.role==='ADMIN'?`
<button class="nav-item" data-page="dashboard"><span>⌂</span> Admin Dashboard</button><button class="nav-item" data-page="pc-management"><span>▣</span> PC Management</button><button class="nav-item" data-page="users"><span>♙</span> User Management</button><button class="nav-item" data-page="all-bookings"><span>▤</span> All Bookings</button><button class="nav-item" data-page="labs"><span>▥</span> Laboratories</button><button class="nav-item" data-page="profile"><span>◎</span> My Profile</button>`:`
<button class="nav-item" data-page="dashboard"><span>⌂</span> Dashboard</button><button class="nav-item" data-page="book"><span>＋</span> Book a Computer</button><button class="nav-item" data-page="bookings"><span>▣</span> My Bookings</button><button class="nav-item" data-page="labs"><span>▥</span> Laboratories</button><button class="nav-item" data-page="profile"><span>◎</span> My Profile</button>`;n.querySelectorAll('.nav-item').forEach(x=>x.onclick=()=>{page=x.dataset.page;render(page)})}
function render(p){const u=user();if(!u)return auth();const ok=u.role==='ADMIN'?['dashboard','pc-management','users','all-bookings','labs','profile']:['dashboard','book','bookings','labs','profile'];if(!ok.includes(p))p='dashboard';page=p;nav();document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));const titles={dashboard:u.role==='ADMIN'?'Admin Dashboard':'Dashboard',book:'Book a Computer',bookings:'My Bookings',labs:'Laboratories',profile:'My Profile','pc-management':'PC Management',users:'User Management','all-bookings':'All Bookings'};document.getElementById('page-title').textContent=titles[p];const fn={dashboard:u.role==='ADMIN'?adminDash:userDash,book:booking,bookings:bookings,labs:labsPage,profile:profile,'pc-management':pcManage,users:usersPage,'all-bookings':allBookings};document.getElementById('page-content').innerHTML=fn[p]();bind(p)}
function userDash(){const u=user(),bs=read(K.bookings,[]).filter(b=>b.userId===u.userId),up=bs.filter(b=>b.status==='CONFIRMED'&&b.bookingDate>=today()),ready=read(K.pcs,[]).filter(p=>p.status==='READY').length;return `<div class="page-grid"><div class="welcome-banner"><div><p class="eyebrow">WELCOME BACK</p><h2>${esc(u.fullName)}</h2><p>Book a specific ready-to-use computer for your laboratory session.</p></div><button class="btn primary" data-go="book">＋ Book a Computer</button></div><div class="stats-grid"><div class="stat-card"><div class="label">MY BOOKINGS</div><div class="value">${bs.length}</div><div class="sub">All reservations</div></div><div class="stat-card"><div class="label">UPCOMING</div><div class="value">${up.length}</div><div class="sub">Future bookings</div></div><div class="stat-card"><div class="label">READY PCs</div><div class="value">${ready}</div><div class="sub">Currently bookable</div></div><div class="stat-card"><div class="label">ACCOUNT</div><div class="value" style="font-size:18px;margin-top:13px">${u.role}</div><div class="sub">Current role</div></div></div><div class="grid-2"><div class="card"><div class="card-header"><div><h3>Upcoming bookings</h3><p>Your next computer reservations</p></div></div>${up.length?`<div class="table-wrap"><table><thead><tr><th>Computer</th><th>Lab</th><th>Date</th><th>Time</th></tr></thead><tbody>${up.slice(0,5).map(b=>`<tr><td><strong>${esc(b.computerNumber)}</strong></td><td>${esc(b.labName)}</td><td>${b.bookingDate}</td><td>${b.startTime}-${b.endTime}</td></tr>`).join('')}</tbody></table></div>`:'<div class="info-box">No upcoming bookings.</div>'}</div><div class="card"><div class="card-header"><div><h3>Your functions</h3><p>Available for students and lecturers</p></div></div><div class="quick-actions"><button class="action-card" data-go="book"><strong>＋ Book a computer</strong><span>Select one specific ready PC.</span></button><button class="action-card" data-go="bookings"><strong>▣ My bookings</strong><span>View or cancel your bookings.</span></button><button class="action-card" data-go="labs"><strong>▥ Laboratories</strong><span>Check lab capacity and PC readiness.</span></button><button class="action-card" data-go="profile"><strong>◎ My profile</strong><span>Update account information.</span></button></div></div></div></div>`}
function adminDash(){const us=read(K.users,[]),bs=read(K.bookings,[]),ps=read(K.pcs,[]),r=ps.filter(p=>p.status==='READY').length,m=ps.length-r;return `<div class="page-grid"><div class="admin-hero"><div><p class="eyebrow">SYSTEM ADMINISTRATION</p><h2>Computer Lab Control Centre</h2><p>Manage PC availability, users and every reservation in the system.</p></div><button class="btn primary" data-go="pc-management">Manage PCs</button></div><div class="stats-grid"><div class="stat-card"><div class="label">USERS</div><div class="value">${us.length}</div><div class="sub">Registered accounts</div></div><div class="stat-card"><div class="label">BOOKINGS</div><div class="value">${bs.length}</div><div class="sub">All reservations</div></div><div class="stat-card"><div class="label">READY PCs</div><div class="value">${r}</div><div class="sub">Available for booking</div></div><div class="stat-card alert-stat"><div class="label">MAINTENANCE</div><div class="value">${m}</div><div class="sub">Unavailable PCs</div></div></div><div class="admin-grid"><div class="card"><div class="card-header"><div><h3>Administration</h3><p>System-specific functions</p></div></div><div class="quick-actions"><button class="action-card" data-go="pc-management"><strong>▣ PC Management</strong><span>Mark PCs Ready or Under Maintenance.</span></button><button class="action-card" data-go="users"><strong>♙ User Management</strong><span>View all registered users.</span></button><button class="action-card" data-go="all-bookings"><strong>▤ All Bookings</strong><span>Monitor and cancel reservations.</span></button><button class="action-card" data-go="labs"><strong>▥ Laboratories</strong><span>View every lab and its PC status.</span></button></div></div><div class="card"><div class="card-header"><div><h3>Maintenance PCs</h3><p>Currently blocked from booking</p></div></div>${m?`<div class="maintenance-list">${ps.filter(p=>p.status==='MAINTENANCE').slice(0,10).map(p=>`<div class="maintenance-item"><strong>${esc(p.number)}</strong><span>${esc(lab(p.labId).name)}</span><small>${esc(p.maintenanceNote||'Under maintenance')}</small></div>`).join('')}</div>`:'<div class="info-box">All PCs are Ready for Use.</div>'}</div></div></div>`}
function booking(){return `<div class="booking-layout"><div class="card"><div class="card-header"><div><h3>Book an individual computer</h3><p>Students and lecturers must select a specific PC. Whole-lab booking is disabled.</p></div></div><form id="booking-form" class="form-stack"><label>Booking Date<input id="bdate" type="date" min="${today()}" value="${today()}" required></label><label>Time Slot<select id="bslot">${slots.map(s=>`<option value="${s.id}">${s.label}</option>`).join('')}</select></label><label>Laboratory<select id="blab" required><option value="">Select laboratory</option>${labs.map(l=>`<option value="${l.id}">${l.name} — ${l.capacity} PCs</option>`).join('')}</select></label><label>Computer<select id="bpc" required><option value="">Choose date, time and lab first</option></select></label><div id="pcinfo" class="info-box">Only PCs marked <b>READY FOR USE</b> by the administrator can be booked.</div><div class="form-actions"><button class="btn ghost" type="reset">Clear</button><button class="btn primary">Confirm Computer Booking</button></div></form></div><div class="card"><div class="card-header"><div><h3>Booking rules</h3><p>Important information</p></div></div><div class="info-box" style="margin-bottom:12px"><b>One PC per booking:</b> A reservation is linked to one computer.</div><div class="info-box" style="margin-bottom:12px"><b>Maintenance:</b> A PC under maintenance cannot be selected.</div><div class="info-box"><b>No conflicts:</b> The same PC cannot be booked twice in one time slot.</div></div></div>`}
function avail(date,slot,labid){const booked=new Set(read(K.bookings,[]).filter(b=>b.bookingDate===date&&b.slotId===slot&&b.status==='CONFIRMED').map(b=>b.pcId));return read(K.pcs,[]).filter(p=>p.labId===labid&&p.status==='READY'&&!booked.has(p.pcId))}
function updatePC(){const d=document.getElementById('bdate')?.value,s=document.getElementById('bslot')?.value,l=document.getElementById('blab')?.value,sel=document.getElementById('bpc'),info=document.getElementById('pcinfo');if(!sel||!d||!s||!l)return;const a=avail(d,s,l),all=read(K.pcs,[]).filter(p=>p.labId===l),m=all.filter(p=>p.status==='MAINTENANCE').length;sel.innerHTML=a.length?`<option value="">Select a computer</option>${a.map(p=>`<option value="${p.pcId}">${p.number}</option>`).join('')}`:'<option value="">No ready PCs available</option>';sel.disabled=!a.length;info.innerHTML=`<b>${a.length}</b> PC(s) available. ${m} of ${all.length} PC(s) are under maintenance.`}
function saveBooking(e){e.preventDefault();const u=user(),d=document.getElementById('bdate').value,s=document.getElementById('bslot').value,l=document.getElementById('blab').value,pid=document.getElementById('bpc').value,p=read(K.pcs,[]).find(x=>x.pcId===pid),sl=slots.find(x=>x.id===s),ll=lab(l);if(!p||p.status!=='READY')return toast('Select a ready computer.','error');const bs=read(K.bookings,[]);if(bs.some(b=>b.pcId===pid&&b.bookingDate===d&&b.slotId===s&&b.status==='CONFIRMED'))return toast('That PC is already booked for this time.','error');bs.push({bookingId:uid('BK'),userId:u.userId,userName:u.fullName,pcId:pid,computerNumber:p.number,labId:l,labName:ll.name,bookingDate:d,slotId:s,startTime:sl.start,endTime:sl.end,status:'CONFIRMED',createdAt:new Date().toISOString()});write(K.bookings,bs);toast('Computer booking confirmed.','success');render('bookings')}
function bookings(){const u=user(),bs=read(K.bookings,[]).filter(b=>b.userId===u.userId);return `<div class="card"><div class="card-header"><div><h3>My Computer Bookings</h3><p>Every reservation is for one specific computer.</p></div><button class="btn primary" data-go="book">＋ Book a Computer</button></div>${bs.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Computer</th><th>Lab</th><th>Date</th><th>Time</th><th>Status</th><th></th></tr></thead><tbody>${bs.map(b=>`<tr><td>${esc(b.bookingId)}</td><td><strong>${esc(b.computerNumber)}</strong></td><td>${esc(b.labName)}</td><td>${b.bookingDate}</td><td>${b.startTime}-${b.endTime}</td><td><span class="badge ${b.status==='CONFIRMED'?'confirmed':'cancelled'}">${b.status}</span></td><td>${b.status==='CONFIRMED'?`<button class="btn danger cancel" data-id="${b.bookingId}">Cancel</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="info-box">No bookings found.</div>'}</div>`}
function cancel(id){const bs=read(K.bookings,[]),b=bs.find(x=>x.bookingId===id&&x.userId===user().userId);if(!b||!confirm('Cancel this booking?'))return;b.status='CANCELLED';write(K.bookings,bs);render('bookings');toast('Booking cancelled.','success')}
function labsPage(){const ps=read(K.pcs,[]),admin=user().role==='ADMIN';return `<div class="card"><div class="card-header"><div><h3>Laboratories</h3><p>Live PC readiness across the system.</p></div></div><div class="lab-grid">${labs.map(l=>{const a=ps.filter(p=>p.labId===l.id),r=a.filter(p=>p.status==='READY').length;return `<div class="lab-card"><h4>${esc(l.name)}</h4><p>${esc(l.building)} · ${esc(l.floor)}</p><div class="lab-stats"><span><b>${r}</b> Ready</span><span><b>${a.length-r}</b> Maintenance</span></div><div class="progress"><div style="width:${a.length?r/a.length*100:0}%"></div></div><p style="margin-top:12px"><b>Total PCs:</b> ${a.length}</p>${admin?'':`<button class="btn secondary full labbook" data-lab="${l.id}">Book a Computer</button>`}</div>`}).join('')}</div></div>`}
function profile(){const u=user();return `<div class="profile-grid"><div class="card profile-card"><div class="profile-avatar">${initials(u.fullName)}</div><h3>${esc(u.fullName)}</h3><p>${esc(u.userId)} · ${esc(u.email)}</p><span class="badge ${u.role.toLowerCase()}">${u.role}</span></div><div class="card"><div class="card-header"><div><h3>Profile Information</h3><p>Update your personal details.</p></div></div><form id="profile" class="form-stack"><label>Full Name<input id="pname" value="${esc(u.fullName)}" required></label><label>Email<input id="pemail" type="email" value="${esc(u.email)}" required></label><label>User ID<input value="${esc(u.userId)}" disabled></label><label>Role<input value="${esc(u.role)}" disabled></label><div class="form-actions"><button class="btn primary">Save Changes</button></div></form></div></div>`}
function pcManage(){const ps=read(K.pcs,[]),r=ps.filter(p=>p.status==='READY').length,m=ps.length-r;return `<div class="page-grid"><div class="stats-grid"><div class="stat-card"><div class="label">TOTAL PCs</div><div class="value">${ps.length}</div><div class="sub">All laboratories</div></div><div class="stat-card"><div class="label">READY FOR USE</div><div class="value">${r}</div><div class="sub">Students can book</div></div><div class="stat-card alert-stat"><div class="label">UNDER MAINTENANCE</div><div class="value">${m}</div><div class="sub">Blocked from booking</div></div></div><div class="card"><div class="card-header"><div><h3>PC Status Management</h3><p>Change the status of individual computers.</p></div><select id="pcfilter" class="compact-select"><option value="">All laboratories</option>${labs.map(l=>`<option value="${l.id}">${l.name}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Computer</th><th>Lab</th><th>Status</th><th>Maintenance Note</th><th>Action</th></tr></thead><tbody>${ps.map(p=>`<tr data-lab="${p.labId}"><td><strong>${esc(p.number)}</strong><br><small>${esc(p.pcId)}</small></td><td>${esc(lab(p.labId).name)}</td><td><span class="badge ${p.status==='READY'?'confirmed':'maintenance'}">${p.status==='READY'?'READY FOR USE':'UNDER MAINTENANCE'}</span></td><td>${esc(p.maintenanceNote||'—')}</td><td><button class="btn ${p.status==='READY'?'danger':'secondary'} pctoggle" data-id="${p.pcId}">${p.status==='READY'?'Put in Maintenance':'Mark Ready'}</button></td></tr>`).join('')}</tbody></table></div></div></div>`}
function togglePC(id){const ps=read(K.pcs,[]),p=ps.find(x=>x.pcId===id);if(!p)return;if(p.status==='READY'){const n=prompt('Maintenance reason (optional):','Scheduled maintenance');if(n===null)return;p.status='MAINTENANCE';p.maintenanceNote=n||'Under maintenance'}else{p.status='READY';p.maintenanceNote=''}p.updatedAt=new Date().toISOString();write(K.pcs,ps);render('pc-management');toast(`${p.number} is now ${p.status==='READY'?'Ready for Use':'Under Maintenance'}.`,'success')}
function usersPage(){const us=read(K.users,[]);return `<div class="card"><div class="card-header"><div><h3>User Management</h3><p>All registered accounts.</p></div><div class="info-pill">${us.length} users</div></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>User ID</th><th>Email</th><th>Role</th><th>Registered</th></tr></thead><tbody>${us.map(u=>`<tr><td><strong>${esc(u.fullName)}</strong></td><td>${esc(u.userId)}</td><td>${esc(u.email)}</td><td><span class="badge ${u.role.toLowerCase()}">${u.role}</span></td><td>${new Date(u.createdAt).toLocaleDateString()}</td></tr>`).join('')}</tbody></table></div></div>`}
function allBookings(){const bs=read(K.bookings,[]);return `<div class="card"><div class="card-header"><div><h3>All System Bookings</h3><p>Administrator view of every PC reservation.</p></div></div>${bs.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>User</th><th>Computer</th><th>Lab</th><th>Date</th><th>Time</th><th>Status</th><th></th></tr></thead><tbody>${bs.map(b=>`<tr><td>${esc(b.bookingId)}</td><td>${esc(b.userName)}<br><small>${esc(b.userId)}</small></td><td>${esc(b.computerNumber)}</td><td>${esc(b.labName)}</td><td>${b.bookingDate}</td><td>${b.startTime}-${b.endTime}</td><td><span class="badge ${b.status==='CONFIRMED'?'confirmed':'cancelled'}">${b.status}</span></td><td>${b.status==='CONFIRMED'?`<button class="btn danger acancel" data-id="${b.bookingId}">Cancel</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="info-box">No bookings found.</div>'}</div>`}
function acancel(id){const bs=read(K.bookings,[]),b=bs.find(x=>x.bookingId===id);if(!b||!confirm('Cancel this booking?'))return;b.status='CANCELLED';write(K.bookings,bs);render('all-bookings');toast('Booking cancelled by administrator.','success')}
function bind(p){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>render(x.dataset.go));if(p==='book'){['bdate','bslot','blab'].forEach(id=>document.getElementById(id)?.addEventListener('change',updatePC));document.getElementById('booking-form').onsubmit=saveBooking}if(p==='bookings')document.querySelectorAll('.cancel').forEach(x=>x.onclick=()=>cancel(x.dataset.id));if(p==='labs')document.querySelectorAll('.labbook').forEach(x=>x.onclick=()=>{render('book');setTimeout(()=>{document.getElementById('blab').value=x.dataset.lab;updatePC()},0)});if(p==='profile')document.getElementById('profile').onsubmit=e=>{e.preventDefault();const us=read(K.users,[]),u=user(),x=us.find(a=>a.userId===u.userId);x.fullName=document.getElementById('pname').value.trim();x.email=document.getElementById('pemail').value.trim().toLowerCase();write(K.users,us);app();toast('Profile updated.','success')};if(p==='pc-management'){document.querySelectorAll('.pctoggle').forEach(x=>x.onclick=()=>togglePC(x.dataset.id));document.getElementById('pcfilter').onchange=e=>document.querySelectorAll('tbody tr[data-lab]').forEach(r=>r.style.display=!e.target.value||r.dataset.lab===e.target.value?'':'none')};if(p==='all-bookings')document.querySelectorAll('.acancel').forEach(x=>x.onclick=()=>acancel(x.dataset.id))}
function bindAuth(){document.querySelectorAll('.auth-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.auth-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.auth+'-panel').classList.add('active')});document.getElementById('login-form').onsubmit=e=>{e.preventDefault();const id=document.getElementById('login-identifier').value.trim().toLowerCase(),pw=document.getElementById('login-password').value,u=read(K.users,[]).find(x=>(x.userId.toLowerCase()===id||x.email.toLowerCase()===id)&&x.password===pw);if(!u)return toast('Invalid login details.','error');localStorage.setItem(K.session,u.userId);page='dashboard';app();toast(`Welcome, ${u.fullName}.`,'success');e.target.reset()};document.getElementById('register-form').onsubmit=e=>{e.preventDefault();const us=read(K.users,[]),id=document.getElementById('reg-userid').value.trim(),email=document.getElementById('reg-email').value.trim().toLowerCase(),pw=document.getElementById('reg-password').value;if(us.some(x=>x.userId.toLowerCase()===id.toLowerCase()))return toast('User ID already exists.','error');if(us.some(x=>x.email.toLowerCase()===email))return toast('Email already exists.','error');if(pw!==document.getElementById('reg-confirm').value)return toast('Passwords do not match.','error');if(pw.length<6)return toast('Password must be at least 6 characters.','error');us.push({userId:id,fullName:document.getElementById('reg-name').value.trim(),email,password:pw,role:document.getElementById('reg-role').value,createdAt:new Date().toISOString()});write(K.users,us);e.target.reset();document.querySelector('[data-auth="login"]').click();document.getElementById('login-identifier').value=id;toast('Registration successful.','success')};document.getElementById('logout-btn').onclick=()=>{localStorage.removeItem(K.session);auth()}}
seed();document.addEventListener('DOMContentLoaded',()=>{bindAuth();user()?app():auth()});
